config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'tags/index'
  get 'tags/show'
  get 'categories/index'
  get 'categories/show'
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
  :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
  }


  get 'welcome', to: 'welcome#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy] 
  end

  resources :users, only: [:index, :show, :edit] do
    resources :articles
    resources :favorites, only: :index
  end


  resources :tags, only: [:index, :show] 
  get 'home', to: 'articles#index'

  authenticated :user do
    root :to => 'articles#index', :as => "user_authenticated_root"
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user

  has_many :comments

  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  has_many :favorites
  has_many :fav_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :nationality, presence: true
  validates :introduction, length: { maximum: 200 }
  
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :favorites
  has_many :fav_articles, through: :favorites, source: :article

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]   

  def index
    @articles = Article.all.order('created_at DESC')

  end
  
  def show
    @comments = @article.comments
    @comment = Comment.new
    @favorite = current_user.favorites.find_by(article_id: @article.id)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def new
    @article = current_user.articles.build
    @categories = Category.all
  end

  def create
    @article = current_user.articles.build(article_params)


    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, tag_ids: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show]

  def index
    @categories = Category.all
  end

  def show

  end

  private
  
  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end

  end

  def destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :article_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @favorites = @user.fav_articles
  end

  def create
    favorite = current_user.favorites.build(article_id: params[:article_id])
    favorite.save
    # redirect_to articles_path
    redirect_back(fallback_location: root_path)
  end

  def destroy
    favorite = Favorite.find_by(article_id: params[:article_id], user_id: current_user.id)
    favorite.destroy
    # redirect_to articles_path
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all.order('created_at DESC')
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except:[:index]
  
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:index]

  def index
    @users = User.all.order("created_at DESC")

  end

  def show
    @user = User.find(params[:id])
    @articles = Article.where(user_id: params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  layout 'application'

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Dive into Miyazaki"
    title = @page_title + ' - ' + title if @page_title
    title
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<div class="border p-5 bg-white">
    <%= form_with model: @article do |f| %>
    
        <div class="form-group">
            <%= f.label :title, "What is the title of your post?" %>
            <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :body, "Write whatever you like in English!" %>
            <%= f.text_area :body, size: "20x10",class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :tag, "Choose tags!" %>
            <div>
                <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
                    <%= tag.label do %>
                        <%= tag.check_box %>
                        <%= tag.text %>
                    <% end %>
                <% end %>
            </div>
        </div>

        <div class="form-group">
            
            <%= f.label :image,  "Choose a picture!", class:'image_label' do %>
                <div class="prev-contents">
                    <% if @article.image? %>
                        <div class="prev-content">
                            <%= image_tag @article.image.thum.url, alt: "preview", class: "prev-image" %>
                        </div>
                    <% else %>
                        <%= icon('fas', 'image', class: "photo-icon") %>
                    <% end %>
                </div>
                <%= f.file_field :image, class: 'image_form_contents_field hidden_file' %>
            
            <% end %>
        </div>

        <div class="text-center">
            <%= f.submit "Post it !", class: "btn btn-blue" %>
        </div>
    
    <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<% @page_title = 'Travel Guide Created by Miyazaki Students' %>

<div class="row mb-4 w-100 mx-auto">
    <% @articles.each do |article| %>
        <div class="card col-lg-5 col-sm-10 mb-4 shadow-sm mx-auto p-0">
            <% if article.image? %>
                <%= image_tag article.image.thum.url, class:"thumb" %>
            <% end %>
            <div class="p-3">
                <h2 class="card-article-title"><%= link_to article.title, article_path(article)%></h2>
                <p class="card-article-user"><a href="users/<%= article.user_id %>"><%= article.user.username %></a></p>
                <p class="card-article-date"><%= article.created_at.strftime("%B %d, %Y") %></p>
                <p class="card-article-body"><%= article.body.truncate(120) %></p>
                <% if user_signed_in? %>
                    <% if article.favorited_by?(current_user) %>
                        <p class="card-article-favorite">❤︎：<%= link_to article.favorites.count, article_favorites_path(article.id), method: :delete  %></p>
                    <% else %>
                        <p class="card-article-favorite">❤︎：<%= link_to article.favorites.count, article_favorites_path(article.id), method: :post %></p>
                    <% end %>
                <% else %>
                    <p class="card-article-favorite">❤︎：<%= article.favorites.count %></p>
                <% end %>
                <p class="card-article-comment"><%= pluralize(article.comments.count, "comment") %></p>
            </div>
        </div>
    <% end %>
</div>

<div class="text-center">
    <%= link_to "Post a Column", new_article_path, class: 'btn btn-blue' %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mb-4">Create a new post</h1>


<%= render 'form' %>

app/views/articles/show.html.erb
<article>
    <% if user_signed_in? && @article.user_id == current_user.id %>
        <div class="btn-groups mb-3 text-right">
            <%= link_to "Edit", edit_article_path(@article), class: 'pr-2' %> | 
            <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: 'Are you sure?'}, class: 'pl-2'  %>
        </div>

    <% end %>
    <h1 class="text-head"><%= @article.title %></h1>
    <ul class="article-info">
        <li><%= @article.created_at.strftime("%B %d, %Y") %></li>
        <% @article.tags.each do |tag| %>
        <li><%= link_to tag.name, tag_path(tag.id) %></li>
        <% end %>
    </ul>


    <% if @article.image? %>
        <%= image_tag @article.image.url, class: "article-image" %>
    <% end %>

    <p class="article-content"><%= @article.body %></p>

    <p class="article-author">Written by <%= link_to @article.user.username, user_path(@article.user) %></p>


</article>

<% if user_signed_in? %>
    <% if @article.favorited_by?(current_user) %>
        <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= link_to @article.favorites.count, article_favorites_path(@article.id), method: :delete  %></p>
    <% else %>
        <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= link_to @article.favorites.count, article_favorites_path(@article.id), method: :post %></p>
    <% end %>
<% else %>
    <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= @article.favorites.count %></p>
<% end %>

<%# コメント %>

<div class="comments">
    <h4>Comments</h4>
    <% @comments.each do |comment| %>
    <div class="comment">
        <p class="comment-username"><%= comment.user.username %></p>
        <p class="comment-body"><%= comment.body %></p>
    </div>
    <% end %>
</div>

<div class="comment-form">
    <h5>Post a comment</h5>
    <%= form_for [@article, @comment] do |f| %>
        <%= f.text_area :body %>
        <%= f.hidden_field :article_id, value: @article.id %>
        <br>
        <%= f.submit 'Submit', class: "btn btn-blue" %>
    <% end %>
</div>


<%= link_to "Back", articles_path, class: "btn btn-yellow" %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>

<p><%= link_to category.name, category_path(category.id) %></p>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

<% @category.articles.each do |article| %>
    <p><%= link_to article.title, article_path(article.id) %></p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<h1><%= @user.username %></h1>
<p><%= @user.nationality %></p>

<div class="tablist">
    <ul>
        <li><%= link_to "All Posts", user_path(@user.id) %></li>
        <li><%= link_to "Favorite Posts", user_favorites_path(@user.id) %></li>
    </ul>
</div>

<h2 class="page-title">Your Favorite Posts</h2>
<% if @favorites.exists?%>
    <div class="row mb-4 w-100 mx-auto">
        <% @favorites.each do |article| %>
            <div class="card col-lg-5 col-sm-10 mb-4 shadow-sm mx-auto p-0">
                <% if article.image? %>
                    <%= image_tag article.image.thum.url, class:"thumb" %>
                <% end %>
                <div class="p-3">
                    <h2 class="card-article-title"><%= link_to article.title, article_path(article)%></h2>
                    <p class="card-article-user"><%= link_to article.user.username, user_path(article.user_id) %></a></p>
                    <p class="card-article-date"><%= article.created_at.strftime("%B %d, %Y") %></p>
                    <p class="card-article-body"><%= article.body.truncate(120) %></p>
                    <% if user_signed_in? %>
                        <% if article.favorited_by?(current_user) %>
                            <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= link_to article.favorites.count, article_favorites_path(article.id), method: :delete  %></p>
                        <% else %>
                            <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= link_to article.favorites.count, article_favorites_path(article.id), method: :post %></p>
                        <% end %>
                    <% else %>
                        <p class="card-article-favorite"><i class="fas fa-heart"></i> <%= article.favorites.count %></p>
                    <% end %>
                    <p class="card-article-comment"><i class="fas fa-comment-dots"></i> <%= article.comments.count %></p>
                </div>
            </div>
        <% end %>
    </div>
<% else %>
    <p>No Favorite Posts</p>
<% end %>

app/views/tags/index.html.erb
<h1 class="page-title">All Tags</h1>


<% @tags.each do |tag| %>
    <div class="card text-center mb-3 p-3">
        <h3 class="card-title"><%= tag.name %></h3>
        <p class="card-text"><%= pluralize(tag.articles.count, 'Post') %></p>
        <%= link_to "See All Posts", tag_path(tag.id), class: "card-link" %>
    </div>
<% end %>

app/views/tags/show.html.erb
<h1 class="page-title"><%= @tag.name %></h1>

<% if @tag.articles.exists? %>
    <% @tag.articles.each do |article| %>
            <div class="card col-lg-5 col-sm-10 mb-4 shadow-sm mx-auto p-0">
                <% if article.image? %>
                    <%= image_tag article.image.thum.url, class:"thumb" %>
                <% end %>
                <div class="p-3">
                    <h2 class="card-article-title"><%= link_to article.title, article_path(article)%></h2>
                    <p class="card-article-user"><%= link_to article.user.username, user_path(article.user_id) %></p>
                    <p class="card-article-date"><%= article.created_at.strftime("%B %d, %Y") %></p>
                    <p class="card-article-body"><%= article.body.truncate(120) %></p>
                    <p class="card-article-comment"><%= pluralize(article.comments.count, "comment") %></p>
                </div>
            </div>
    <% end %>
<% else %>
    <p>There is no posts in this tag.</p>
<% end %>

<%= link_to 'Back to All Tags', tags_path, class: "btn btn-secondary" %>