config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'tags/index'
  get 'tags/show'
  get 'categories/index'
  get 'categories/show'
  get 'comments/create'
  get 'comments/destroy'
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'signup'},
  :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
  }


  get 'welcome', to: 'welcome#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy] 
  end

  resources :users, only: [:index, :show, :edit] do
    resources :articles
    resources :favorites, only: :index
  end


  resources :tags, only: [:index, :show] 
  get 'home', to: 'articles#index'

  authenticated :user do
    root :to => 'articles#index', :as => "user_authenticated_root"
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user

  has_many :comments

  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  has_many :favorites
  has_many :fav_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags, dependent: :destroy
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :nationality, presence: true
  validates :introduction, length: { maximum: 200 }
  
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :favorites
  has_many :fav_articles, through: :favorites, source: :article

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]   

  def index
    @articles = Article.all.order('created_at DESC')

  end
  
  def show
    @comments = @article.comments
    @comment = Comment.new
    @favorite = current_user.favorites.find_by(article_id: @article.id)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def new
    @article = current_user.articles.build
    @categories = Category.all
  end

  def create
    @article = current_user.articles.build(article_params)


    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, tag_ids: [])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all.order('created_at DESC')
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except:[:index]
  
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:index]

  def index
    @users = User.all.order("created_at DESC")

  end

  def show
    @user = User.find(params[:id])
    @articles = Article.where(user_id: params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  layout 'application'

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "Dive into Miyazaki"
    title = @page_title + ' - ' + title if @page_title
    title
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/db7b38bbd8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-md">
      <%= link_to "Dive into Miyazaki", root_path, class: 'navbar-logo' %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="menu" class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "All Posts", articles_path %></li>
          <li class="nav-item"><%= link_to "All Tags", tags_path %></li>
          <li class="nav-item"><%= link_to "All Members", users_path %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li class="nav-item"><%= link_to "My Page", user_path(current_user) %></li>
            <li class="nav-item"><%= link_to "New Post", new_article_path %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path %></li>
            <li class="nav-item"><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <header class="mb-5 d-flex justify-content-center flex-column align-items-center">
        <div class="text-center">
          <%= link_to "Dive into Miyazaki", root_path, class: "text-white cover-logo" %>
          <p class="cover-desc">The more you know Miyazaki,<br>the more you want to know this place.</p>
        </div>
    </header>

    <main class="container mb-5">
      <%= yield %>
    </main>

    <footer>
      <p class="link-logo">
        <a href="https://www.pref.miyazaki.lg.jp/">
          <%= image_tag 'miyazaki-logo.jpg' %>
        </a>
      </p>
      <p class="copyright">Copyright © 2020 diveintomiyazaki.com</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-md">
      <%= link_to "Dive into Miyazaki", root_path, class: 'navbar-logo' %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="menu" class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "All Posts", articles_path %></li>
          <li class="nav-item"><%= link_to "All Tags", tags_path %></li>
          <li class="nav-item"><%= link_to "All Members", users_path %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <li class="nav-item"><%= link_to "My Page", user_path(current_user) %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign up", new_user_registration_path %></li>
            <li class="nav-item"><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <header class="mb-5 d-flex justify-content-center flex-column align-items-center">
        <div class="text-center">
          <%= link_to "Dive into Miyazaki", root_path, class: "text-white cover-logo" %>
          <p class="cover-desc">The more you know Miyazaki,<br>the more you want to know this place.</p>
        </div>
    </header>

    <main class="container mb-5">
      <%= yield %>
    </main>

    <footer>
      <p class="link-logo">
        <a href="https://www.pref.miyazaki.lg.jp/">
          <%= image_tag 'miyazaki-logo.jpg' %>
        </a>
      </p>
      <p class="copyright">Copyright © 2020 diveintomiyazaki.com</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>

  </body>
</html>